In [4]:
###CONSTRUCTOR OF PARENT CLASS(nn.Module)
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3) ####Input to hidden linear layer
        self.relu=nn.ReLU() ##### relu activation for hidden layer
        self.linear2=nn.Linear(3,1)##########hidden to output linear layer
        self.sigmoid=nn.Sigmoid() #######1 outyput sigmod
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [6]:
import torch

In [7]:
data =torch.rand(10,5)

In [8]:
data

tensor([[0.4093, 0.2674, 0.6415, 0.2757, 0.4054],
        [0.5912, 0.6819, 0.1437, 0.9264, 0.2080],
        [0.7487, 0.2745, 0.8128, 0.2344, 0.1250],
        [0.3177, 0.6886, 0.7827, 0.4149, 0.0689],
        [0.3313, 0.6711, 0.0158, 0.4640, 0.8885],
        [0.0573, 0.9298, 0.0872, 0.1065, 0.1464],
        [0.5114, 0.2732, 0.7041, 0.3813, 0.7304],
        [0.0926, 0.5981, 0.0138, 0.5974, 0.4873],
        [0.0381, 0.3055, 0.1402, 0.5640, 0.1465],
        [0.0462, 0.4870, 0.0519, 0.1083, 0.4971]])

In [9]:
data.shape ###10 representing rows and 5 columns

torch.Size([10, 5])

In [11]:
data.shape[1] #### 5 columns act as features which we need to assign to linear1 function

5

In [10]:
###create object
model = Model(data.shape[1])

In [12]:
####forward pass
model(data) ###final value after calculation ### as per response of forward pass we can perform backward propogation

tensor([[0.3681],
        [0.3740],
        [0.3678],
        [0.3597],
        [0.3699],
        [0.3606],
        [0.3682],
        [0.3740],
        [0.3740],
        [0.3633]], grad_fn=<SigmoidBackward0>)

In [13]:
####to check weights and baisses (5*3=15 weights)
model.linear1.weight

Parameter containing:
tensor([[-0.1749,  0.2560,  0.4242, -0.0305, -0.3049],
        [-0.2678,  0.1129,  0.1848, -0.3789,  0.2582],
        [-0.0409,  0.0618,  0.3786, -0.1953, -0.0972]], requires_grad=True)

In [14]:
####to check baisses (3*1)
model.linear1.bias

Parameter containing:
tensor([-0.0858,  0.0160, -0.4429], requires_grad=True)

In [15]:
###weight for second linear = 3 weight
model.linear2.weight

Parameter containing:
tensor([[-0.1727, -0.2941, -0.2816]], requires_grad=True)

In [16]:
####how many bais from second = 1 baiss
model.linear2.bias

Parameter containing:
tensor([-0.5152], requires_grad=True)

In [17]:
### as per response of forward pass we can perform backward propogation
###pytorch give one more sequential method to do this everything in one shot
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out


In [18]:
data=torch.rand(10,5)

In [19]:
model =Model(data.shape[1])

In [20]:
model.forward(data) ### calling squentially

tensor([[0.5363],
        [0.5031],
        [0.5324],
        [0.5161],
        [0.5208],
        [0.5135],
        [0.5254],
        [0.5509],
        [0.5261],
        [0.5232]], grad_fn=<SigmoidBackward0>)

In [23]:
!pip install torchinfo

In [24]:
from torchinfo import summary

In [25]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [28]:
####train the model with data
data=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")


In [29]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [30]:
data.shape

(569, 33)

In [31]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [32]:
data.drop(columns=['id','Unnamed: 32'],inplace=True)

In [33]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

#Benign= no cancer
#malignant=cancer

In [34]:
data["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [35]:
data.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [36]:
data.iloc[:, 1:]

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [37]:
###now on top of this target column we need to train the model and lets see the pipeline how it works

###1) now segregate the test data
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:, 0], test_size=0.2)

In [38]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
99        14.420         19.77           94.48      642.5          0.09752   
121       18.660         17.12          121.40     1077.0          0.10540   
314        8.597         18.60           54.09      221.2          0.10740   
468       17.600         23.33          119.00      980.5          0.09289   
125       13.850         17.21           88.44      588.7          0.08785   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
99            0.11410         0.09388              0.05839         0.1879   
121           0.11000         0.14570              0.08665         0.1966   
314           0.05847         0.00000              0.00000         0.2163   
468           0.20040         0.21360              0.10020         0.1696   
125           0.06136         0.01420              0.01141         0.1614   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
99                  0.06390  ...        16.330          30.86   
121                 0.06213  ...        22.250          24.90   
314                 0.07359  ...         8.952          22.44   
468                 0.07369  ...        21.570          28.87   
125                 0.05890  ...        15.490          23.58   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
99            109.50       826.4            0.1431            0.30260   
121           145.40      1549.0            0.1503            0.22910   
314            56.65       240.1            0.1347            0.07767   
468           143.60      1437.0            0.1207            0.47850   
125           100.30       725.9            0.1157            0.13500   

     concavity_worst  concave points_worst  symmetry_worst  \
99           0.31940               0.15650          0.2718   
121          0.32720               0.16740          0.2894   
314          0.00000               0.00000          0.3142   
468          0.51650               0.19960          0.2301   
125          0.08115               0.05104          0.2364   

     fractal_dimension_worst  
99                   0.09353  
121                  0.08456  
314                  0.08116  
468                  0.12240  
125                  0.07182  

[5 rows x 30 columns]

In [41]:
#now on top of this target column we need to train artificial neural network and lets see the pipeline how it works

#1) import standardScalar - this is applied on data for scaling the data

#2) Label encoder fo output column

#3)now segregate the test data

scaler=StandardScaler() ####train neural
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [42]:
X_train

array([[ 0.06966142,  0.0876401 ,  0.08739181, ...,  0.61031186,
        -0.31007137,  0.47650104],
       [ 1.27136045, -0.52061437,  1.19167652, ...,  0.77535933,
        -0.03524248, -0.00302306],
       [-1.58069081, -0.18090999, -1.56944547, ..., -1.75940639,
         0.35201641, -0.18478247],
       ...,
       [ 0.31340226,  0.69359927,  0.26952495, ...,  0.09699909,
         0.40354682,  0.70049278],
       [-0.08338516, -0.74096316, -0.16324636, ..., -1.07241523,
        -0.58490025, -0.98292012],
       [-0.5992088 , -1.52595572, -0.63621823, ..., -0.69568302,
        -0.62862303, -0.30132233]])

In [43]:
X_test

array([[-0.55669586, -1.21609024, -0.55663753, ..., -0.37543036,
        -0.37409401,  0.19370478],
       [ 1.42157283, -0.79145976,  1.39267931, ...,  0.93132162,
        -0.7394915 , -1.18178629],
       [-0.457499  , -0.07303089, -0.42783166, ..., -0.3565029 ,
        -1.24230345, -0.68087874],
       ...,
       [-0.3951467 , -0.66521826, -0.4503932 , ..., -0.86875573,
        -0.83318317, -1.09678704],
       [-0.69840565, -0.62390287, -0.7231827 , ..., -0.70431394,
        -1.8809683 , -0.59801783],
       [ 0.45511205, -0.34387628,  0.46150313, ...,  0.98129012,
         1.36700946,  1.07898002]])

In [44]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,

In [45]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1])

In [46]:
#Now convert numpy into tensors
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [47]:
X_train_tensor.dtype

torch.float32

In [48]:
type(X_train_tensor)

torch.Tensor

In [50]:
#✅ Summary
#StandardScaler Normalizes features to help the model learn faster and better

#LabelEncoderConverts string/categorical labels to integers for model compatibility

In [51]:
###create neural network
class MySimpleNN(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [52]:
data.shape

(569, 31)

In [53]:
X_train.shape[1]

30

In [61]:
#Now define below values

#learning rate=0.1

#epoch=1 forward propogation and 1 backward propogation (hyperparameter)
#neural network gives loss function as well
##initialise loss function
##we have 2 classes in the output(Bening and melanin) so we have to select binary class entropy loss function

In [56]:
learning_rate=0.01
epochs=25

In [57]:
loss_function=nn.BCELoss()

In [62]:
model=MySimpleNN(X_train.shape[1])###call the model with name   "MySimpleNN" ### There will be 30 node

optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate) ###Stochastic Gradient Descent
#It’s one of the most common optimization algorithms to update the weights of your neural network during training.

In [63]:
for epoch in range(epochs):
    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1)) ###convert normal tensor into 1dimension tensor

    # clear gradients
    optimizer.zero_grad() ###whenever we perform forward and backward propogation at each step. it updates gradient, it will reset

    loss.backward()### on top of loss we will call backward ##only for backward graph dL/dW =dL/dPred*Dpred/dZ*dZ/dW

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7224007248878479
Epoch: 2, Loss: 0.7206147313117981
Epoch: 3, Loss: 0.71882563829422
Epoch: 4, Loss: 0.717035174369812
Epoch: 5, Loss: 0.7152426838874817
Epoch: 6, Loss: 0.7134437561035156
Epoch: 7, Loss: 0.7116390466690063
Epoch: 8, Loss: 0.7098297476768494
Epoch: 9, Loss: 0.7080256342887878
Epoch: 10, Loss: 0.706227719783783
Epoch: 11, Loss: 0.7044233083724976
Epoch: 12, Loss: 0.7026149034500122
Epoch: 13, Loss: 0.7007982730865479
Epoch: 14, Loss: 0.6989675164222717
Epoch: 15, Loss: 0.6971275806427002
Epoch: 16, Loss: 0.6952919363975525
Epoch: 17, Loss: 0.6934557557106018
Epoch: 18, Loss: 0.691628098487854
Epoch: 19, Loss: 0.6898034811019897
Epoch: 20, Loss: 0.6879802346229553
Epoch: 21, Loss: 0.6861574053764343
Epoch: 22, Loss: 0.6843246221542358
Epoch: 23, Loss: 0.6824861764907837
Epoch: 24, Loss: 0.6806344389915466
Epoch: 25, Loss: 0.6787710785865784


In [64]:
X_test_tensor.shape

torch.Size([114, 30])

In [65]:
X_test_tensor[1]

tensor([ 1.4216, -0.7915,  1.3927,  1.4007, -0.7016,  0.2201,  0.3485,  1.1860,
        -0.2675, -1.5743,  2.0897, -1.0957,  1.9757,  1.6578,  0.7892,  0.2371,
         0.3678,  2.6370,  1.3123, -0.1798,  1.1917, -1.2947,  1.1619,  1.0759,
        -0.8985, -0.3657, -0.2485,  0.9313, -0.7395, -1.1818])

In [66]:
model.forward(X_test_tensor[1])

tensor([0.6735], grad_fn=<SigmoidBackward0>)

In [67]:
y_pred=model.forward(X_test_tensor[1])

In [68]:
y_pred

tensor([0.6735], grad_fn=<SigmoidBackward0>)

In [69]:
y_pred=(y_pred>0.5).float()

In [70]:
y_test_tensor=y_test_tensor[0]

In [71]:
(y_pred==y_test_tensor).float()

tensor([0.])

In [74]:
###to evaluate model
with torch.no_grad():####no need to calculate the gradient while performing prediction
    y_pred=model.forward(X_test_tensor) ###pass data to the trained  model
    y_pred=(y_pred>0.5).float()####more than 0.5 mark as 1, if less then no need to mark
    accuracy = (y_pred == y_test_tensor).float().mean()######check acuracy of actual and predicted value
    print(f'Accuracy: {accuracy.item()}')



Accuracy: 0.05263157933950424


In [73]:
summary(model)

Layer (type:depth-idx)                   Param #
MySimpleNN                               --
├─Linear: 1-1                            93
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 97
Trainable params: 97
Non-trainable params: 0

In [75]:
##For LLM Model >> pretraining (LM), SUPERVISEDFINE TUNING
##LLM model is already done , we just use those model with API